server:
  port: 8888

spring:
  mvc:
    view:
      suffix: .html
      prefix: /
    hiddenmethod:
      filter:
        enable: true
      
  datasource:
    url: jdbc:mysql://localhost:3306/demo01?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: hsp
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.macletek.demo01.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    
